FROM node:20-alpine AS base

# ---- deps ----
FROM base AS deps
WORKDIR /app

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN yarn config set registry https://registry.npmmirror.com
RUN yarn

# ---- builder ----
FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN mv /app/envConfig/.env.development /app/.env.production

RUN yarn build

# ---- Release ----
FROM base AS release
WORKDIR /app
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3001
ENV PORT 3001

CMD node server.js